# Generated by Django 3.1.2 on 2020-11-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subject_name',
            new_name='topic_name',
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Topic Description'),
        ),
    ]
